version: 2
jobs:
  build_php7.4:
    docker:
      - image: circleci/php:7.4.6
    steps:
      - checkout
      - run: COMPOSER=composer.json composer install
      - run: COMPOSER=composer.json composer test
      - run: COMPOSER=composer.json composer phpstan
      - run: COMPOSER=composer.json composer lint
  build_php7.1:
    docker:
      - image: circleci/php:7.1-browsers
    steps:
      - checkout
      - run: COMPOSER=composer.json composer install
      - run: COMPOSER=composer.json composer test
      - run: COMPOSER=composer.json composer phpstan
      - run: COMPOSER=composer.json composer lint
workflows:
  version: 2
  build_php_versions:
    jobs:
      - build_php7.1
      - build_php7.4
